---
title: "Graphs"
author: "Emily Axelsen"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(gt)
library(tidyverse)
```

```{r Reading in Data}
final_gun_violence_data <- readRDS("final data/final_data.rds")
```

### 2013 Gun Violence Graphics

```{r Graph Showing Permits Granted Per Month in 2013}
final_gun_violence_data %>%
  filter(year == 2013) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2013",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")

ggsave("2013graph.png", path ="gun_violence")
```


```{r}
permit_2013 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "06") %>%
  filter(year == 2013) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


A <- ggplot(permit_2013, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in June, 2013",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in June, 2013",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph}
A
ggsave("2013graph2.png", path ="gun_violence")
```

```{r}

n_incidentsAAA <- final_gun_violence_data %>%
  filter(year == 2013) %>%
  count(state) %>%
  arrange(desc(n)) %>%
  gt() %>%
  cols_label(
    n = "Number of Incidents",
    state = "State") %>%
  tab_header(title = "Number of Gun Violence Incidents In June 2013", 
             subtitle = "The top ten states that granted the highest number of permits are formatted in \nbold text and with the same color as the 2013 gun permit bar graph.") %>%
  tab_style(
    style = list(
      cell_fill(color = "#3ab600"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(3))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#f8766d"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(1))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#ff62bb"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(9))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#01bec4"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(8))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#01afff"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(2))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#02bf7d"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(13))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#e86bf3"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(12))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#a2a500"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(14))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#d89000"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(22))) %>%
  tab_style(
    style = list(
      cell_fill(color = "#9690ff"),
      cell_text(weight = "bold")
      ),
    locations = cells_data(
      columns = vars(state, n),
      rows = c(14)))

```


```{r}
n_incidentsAAA
ggsave("2013gt.png", path ="gun_violence")  
```


### 2014 Gun Violence Graphics


```{r Graph Showing Permits Granted Per Month in 2014}
final_gun_violence_data %>%
  filter(year == 2014) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2014",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")

ggsave("2014graph.png", path ="gun_violence")
#COMMAS
```


```{r}
permit_2014 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "03") %>%
  filter(year == 2014) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


B <- ggplot(permit_2014, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in March, 2014",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in March, 2014",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph2}
B

ggsave("2014graph2.png", path ="gun_violence")
```


### 2015 Gun Violence Graphics:

```{r Graph Showing Permits Granted Per Month in 2015}
final_gun_violence_data %>%
  filter(year == 2015) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2015",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")

ggsave("2015graph.png", path ="gun_violence")
```


```{r}
permit_2015 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "12") %>%
  filter(year == 2015) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


C <- ggplot(permit_2015, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in December, 2015",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in December, 2015",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph3}
C

ggsave("2015graph2.png", path ="gun_violence")
```

### 2016 Gun Violence Graphics:

```{r Graph Showing Permits Granted Per Month in 2016}
final_gun_violence_data %>%
  filter(year == 2016) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2016",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")
ggsave("2016graph.png", path ="gun_violence")
```


```{r}
permit_2016 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "03") %>%
  filter(year == 2016) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


D <- ggplot(permit_2016, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in March, 2016",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in March, 2016",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph4}
D
ggsave("2014graph2.png", path ="gun_violence")
```

### 2017 Gun Violence Graphics:

```{r Graph Showing Permits Granted Per Month in 2017}
final_gun_violence_data %>%
  filter(year == 2017) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2017",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")
ggsave("2017graph.png", path ="gun_violence")
```


```{r}
permit_2017 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "03") %>%
  filter(year == 2017) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


E <- ggplot(permit_2017, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in March, 2017",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in March, 2017",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph5}
E
ggsave("2017graph2.png", path ="gun_violence")
```

### 2018 Gun Violence Graphics:

```{r Graph Showing Permits Granted Per Month in 2018}
final_gun_violence_data %>%
  filter(year == 2018) %>%
  ggplot(aes(x = month, y = permit, fill = month)) + 
  geom_bar(stat = 'identity', show.legend = FALSE) +
  labs(x = "Month", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per Month in 2018",
       subtitle = "Do Gun Permits Sold Increase in Summer Months?",
       caption = "Source: The National Instant Criminal Background Check System")
```


```{r}
permit_2018 <- final_gun_violence_data %>%
  select(state, permit, year, month) %>%
  filter(month == "03") %>%
  filter(year == 2018) %>%
  unique() %>%
  arrange(desc(permit))  %>%
  slice(1:10)


G <- ggplot(permit_2018, aes(x = reorder(state, permit), y = permit, fill = state)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "State", 
       y = "Number of Permits Granted",
       title = "The Number of Gun Permits Granted Per State in March, 2018",
       subtitle = "The 10 States With That Granted The Highest Number of Permits in March, 2018",
       caption = "Source: The National Instant Criminal Background Check System")
```

```{r Printing Graph6}
G
```

#Linear Regression Plot:

```{r}
n_incidents1 <- final_gun_violence_data %>%
  count(state) %>%
  arrange(desc(n)) 

permit1 <- final_gun_violence_data %>%
  group_by(year, state, permit, population) %>% 
  summarise(n_incidents = n()) 

sum(permit1$n_incidents)

hist(permit1$n_incidents)

incident_permit_data <- inner_join(n_incidents1, permit1, by = "state")

```


```{r}
permit1 %>%
  ggplot(aes(x = permit, y = n_incidents, color = state)) +
  geom_jitter(show.legend = FALSE) +
  geom_smooth(method = 'lm', se = F, col = 'black') +
    labs(x = "Number of Gun Violence Incidents", 
       y = "Average Permits Granted Per Month",
       title = "Impact of Permits Granted on Number of Gun Violence Incidents",
       subtitle = "An Analysis of the 50 US States",
       caption = "Source: The National Instant Criminal Background Check System and ")

m1 <- lm(n_incidents ~ permit + population, data = permit1)

summary(m1)


```

```{r}
library(coefplot)
coefplot(m1)
```


